version: "3.9"

services:
    rabbitmq:
        image: rabbitmq:3.8-management-alpine
        ports:
            - 15672:15672
        environment:
            RABBITMQ_SSL_CACERTFILE: /rootCA.pem
            RABBITMQ_SSL_CERTFILE: /rootCA.pem
            RABBITMQ_SSL_KEYFILE: /rootCA.key
            RABBITMQ_SSL_VERIFY: verify_none
            RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: "false"
        volumes:
          - "./certs/rootCA.pem:/rootCA.pem:ro"
          - "./certs/rootCA.key:/rootCA.key:ro"
    celery:
        build:
          context: .
          dockerfile: Dockerfile
        depends_on:
            - rabbitmq
        volumes:
            - ./celery/celery/:/celery_app/celery/celery/
            - ./py-amqp/amqp/:/celery_app/py-amqp/amqp/
            - ./kombu/kombu/:/celery_app/kombu/kombu/
            - ./billiard/billiard/:/celery_app/billiard/billiard/
            - ./tasks.py:/celery_app/tasks.py
